version: '3.8'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=sqs,s3
      - DEBUG=1
    volumes:
      - ./init-aws:/docker-entrypoint-initaws.d