cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      access-key: access_key
      secret-key: secret_key
    queue:
      uri: http://localhost:4566
      name: default-queue
    end-point:
      uri: http://localhost:4566


consumer:
  sqs:
    message:
      default-queue-name: 'default-queue'
      s3-create-file: 'upload-file-event-sqs'
      s3-delete-file: 'delete-file-event-sqs'
